---
- name: brew update & upgrade
  homebrew: update_homebrew=yes upgrade_all=yes

- name: brew taps 
  homebrew_tap: name={{item}} state=present 
  with_items: "{{ brew_taps }}"

- name: brew cask
  homebrew_cask: name={{item}} state=present 
  with_items: "{{ brew_cask_programs }}"

- name: brew install
  homebrew: name={{item}} state=present
  with_items: "{{ brew_packages }}"